this is level one package
Major-Lag98/Golf-N-Stuff pull request #36
Opened 2023-02-11 03:12 UTC by taj262

2023-02-11 03:32 UTC, Major-Lag98 requested changes
Two things.

I imported your level and took a look but I think it would be better if you just commit your level 1 scene instead of the package. This would make it easier for others to edit it without the need for package import.

I noticed that instead of leaving the tracks at a scale of 1 you scaled them to 16 and left the parent scaled to 1. Its should be the other way around. Build small and scale up. Makes it easier to edit tracks if needed.

Make these changes and I can accept your pull.

2023-02-11 09:13 UTC, taj262 commented
changes completed - scene for level one call final level one, in scenes folder

2023-02-13 21:21 UTC, Major-Lag98 approved these changes
Looks good, good job

2023-02-13 21:37 UTC, kristiana11 approved these changes

2023-02-13 21:37 UTC, merged